yay -S pipewire --needed
yay -S gst-plugin-pipewire --needed
yay -S libpipewire02 --needed
yay -S pipewire-alsa --needed
yay -S pipewire-jack --needed
yay -S pipewire-pulse --needed
yay -S pipewire-zeroconf --needed
yay -S wireplumber --needed
yay -S lib32-pipewire --needed
yay -S lib32-pipewire-jack --needed
yay -S pipewire-jack-replacement --needed
yay -S easyeffects --needed
